services:
    training_first_theme.layout.data_provider.weather:
        class: 'Training\Bundle\FirstThemeBundle\Layout\DataProvider\WeatherDataProvider'
        tags:
            - { name: layout.data_provider, alias: training_first_theme_weather }
