action_groups:
    custom_b2b_flow_checkout_place_order:
        parameters:
            checkout:
                type: Oro\Bundle\CheckoutBundle\Entity\Checkout
# CUSTOMIZATION START
            contact_name:
                default: null
            contact_phone:
                default: null
# CUSTOMIZATION END
        actions:
            - '@assign_value':
                  conditions:
                      '@equal': [$.checkout.shipToBillingAddress, false]
                  parameters: [$.shippingAddress, $.checkout.shippingAddress]
            - '@assign_value':
                  conditions:
                      '@equal': [$.checkout.shipToBillingAddress, true]
                  parameters: [$.shippingAddress, $.checkout.billingAddress]

            # Place order
            - '@get_class_name':
                  object: $.checkout.sourceEntity.sourceDocument
                  attribute: $.sourceDocumentEntityClassName
            - '@duplicate':
                  target: $.checkout.billingAddress
                  attribute: $.billingAddress
                  settings:
                      - [[setNull], [propertyName, [id]]]
                      - [[keep], [propertyName, [customerAddress]]]
                      - [[keep], [propertyName, [customerUserAddress]]]
                      - [[keep], [propertyName, [city]]]
                      - [[keep], [propertyName, [country]]]
                      - [[keep], [propertyName, [region]]]
                      - [[keep], [propertyName, [organization]]]
                      - [[shallowCopy], [propertyType, ['\DateTime']]]
            - '@flush_entity': $.billingAddress

            - '@duplicate':
                  target: $.shippingAddress
                  attribute: $.shippingAddress
                  settings:
                      - [[setNull], [propertyName, [id]]]
                      - [[keep], [propertyName, [customerAddress]]]
                      - [[keep], [propertyName, [customerUserAddress]]]
                      - [[keep], [propertyName, [city]]]
                      - [[keep], [propertyName, [country]]]
                      - [[keep], [propertyName, [region]]]
                      - [[keep], [propertyName, [organization]]]
                      - [[shallowCopy], [propertyType, ['\DateTime']]]
            - '@flush_entity': $.shippingAddress

            - '@call_service_method':
                  service: oro_payment_term.provider.payment_term
                  method: getCurrentPaymentTerm
                  attribute: $.paymentTerm
            - '@get_order_line_items':
                  attribute: $.lineItems
                  checkout: $.checkout
            - '@create_order':
                  attribute: $.order
                  checkout: $.checkout
                  data:
                      billingAddress: $.billingAddress
                      shippingAddress: $.shippingAddress
                      sourceEntityClass: $.sourceDocumentEntityClassName
                      paymentTerm: $.paymentTerm
                      lineItems: $.lineItems
# CUSTOMIZATION START
                      contactName: $.contact_name
                      contactPhone: $.contact_phone
# CUSTOMIZATION END
            - '@call_service_method':
                  service: oro_order.order.total.total_helper
                  method: fill
                  method_parameters:
                      - $.order
            - '@tree':
                  conditions:
                      '@not_empty': $.checkout.registeredCustomerUser
                  actions:
                      - '@assign_value': [$.order.customerUser, $.checkout.registeredCustomerUser]
                      - '@assign_value': [$.order.customer, $.checkout.registeredCustomerUser.customer]

            - '@flush_entity': $.order
