services:
    _defaults:
        public: true

    Training\Bundle\FrontendTrainingBundle\Controller\Frontend\DashboardController:
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: container.service_subscriber }
