services:
    Training\Bundle\FrontendTrainingBundle\Validator\Constraints\AllowedEmailDomainValidator:
        arguments:
            - '@oro_config.manager'
        tags:
            - { name: validator.constraint_validator }

    Training\Bundle\FrontendTrainingBundle\Controller\Frontend\ShoppingListCleanupController:
        public: true
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
        tags: [ container.service_subscriber ]
