services:
    Training\Bundle\FrontendTrainingBundle\Validator\Constraints\AllowedEmailDomainValidator:
        arguments:
            - '@oro_config.manager'
        tags:
            - { name: validator.constraint_validator }
