configs:
    trainingfrontendtraining/js/app/components/dashboards-component: {}
    trainingfrontendtraining/js/app/datagrid/listener/refresh-grid-listener: {}
dynamic-imports:
    trainingfrontendtraining:
        - 'trainingfrontendtraining/js/app/components/dashboards-component'
        - 'trainingfrontendtraining/js/app/views/dashboards-view'
        - 'trainingfrontendtraining/js/app/views/users-stats-view'
        - 'trainingfrontendtraining/js/app/views/orders-view'
        - 'trainingfrontendtraining/js/app/order-list-collection-service'
        - 'trainingfrontendtraining/js/app/datagrid/listener/refresh-grid-listener'
        - 'trainingfrontendtraining/js/app/components/jquery-plugin-component'
aliases:
    datatables: trainingfrontendtraining/lib/datatables/dataTables.min.js
