aliases:
    datatables: trainingfrontendtraining/lib/datatables/dataTables.min.js

dynamic-imports:
    trainingfrontendtraining:
        - trainingfrontendtraining/js/app/components/jquery-plugin-component
        - trainingfrontendtraining/js/datagrid/builder/csr-badge-shopping-list-flat-data-builder
        - tpl-loader!trainingfrontendtraining/templates/datagrid/row/csr-badge-row.html

map:
    "*":
        oroshoppinglist/js/datagrid/builder/shoppinglist-flat-data-builder: trainingfrontendtraining/js/datagrid/builder/csr-badge-shopping-list-flat-data-builder
    trainingfrontendtraining/js/datagrid/builder/csr-badge-shopping-list-flat-data-builder:
        oroshoppinglist/js/datagrid/builder/shoppinglist-flat-data-builder: oroshoppinglist/js/datagrid/builder/shoppinglist-flat-data-builder
