aliases:
    datatables: trainingfrontendtraining/lib/datatables/dataTables.min.js

app-modules:
    - trainingfrontendtraining/js/app/modules/validator-constraints-module

configs:
    trainingfrontendtraining/js/validator/allowed-email-domain: {}
    trainingfrontendtraining/js/app/components/layout-block-refresh-component: {}

dynamic-imports:
    commons:
        - trainingfrontendtraining/js/validator/allowed-email-domain
    trainingfrontendtraining:
        - trainingfrontendtraining/js/app/components/jquery-plugin-component
        - trainingfrontendtraining/js/app/components/layout-block-refresh-component
        - trainingfrontendtraining/js/datagrid/builder/csr-badge-shopping-list-flat-data-builder
        - tpl-loader!trainingfrontendtraining/templates/datagrid/row/csr-badge-row.html
        - trainingfrontendtraining/js/app/views/custom-product-view

map:
    '*':
        'oroproduct/js/app/views/base-product-view': 'trainingfrontendtraining/js/app/views/custom-product-view'
    'trainingfrontendtraining/js/app/views/custom-product-view':
        'oroproduct/js/app/views/base-product-view': 'oroproduct/js/app/views/base-product-view'
