placeholders:
    items:
        print_order_buttons:
            template: '@@AcmeOrder/Placeholders/printButtons.html.twig'

    placeholders:
        view_navButtons_after:
            items:
                print_order_buttons:
                    order: 10
