navigation:
    menu_config:
        items:
            acme_frontend_libraries_country_index:
                label: acme.frontend_libraries.navigation.country.index.label
                route: acme_frontend_libraries_country_index
                position: 30
                display_children: false
        tree:
            oro_customer_menu_refreshing_teal:
                children:
                    acme_frontend_libraries_country_index: ~

    titles:
        acme_frontend_libraries_country_index:   'acme.frontend_libraries.navigation.country.index.label'
