services:
    TC\Bundle\ProductBundle\EventListener\Datagrid\FrontendProductGridInventoryListener:
        arguments:
            - '@TC\Bundle\ProductBundle\Provider\InventoryLevelProvider'
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.frontend-product-search-grid, method: onBuildBefore }
            - { name: kernel.event_listener, event: oro_datagrid.search_datasource.result.after.frontend-product-search-grid, method: onResultAfter }}

    TC\Bundle\ProductBundle\EventListener\ProductListInventoryListener:
        arguments:
            - '@TC\Bundle\ProductBundle\Provider\InventoryLevelProvider'
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: kernel.event_listener, event: oro_product.product_list.build_query, method: onBuildQuery }
            - { name: kernel.event_listener, event: oro_product.product_list.build_result, method: onBuildResult }

    TC\Bundle\ProductBundle\Provider\InventoryLevelProvider:
        arguments:
            - '@doctrine'
