label: Oro Theme
logo: bundles/acmetheme/themes/oro/images/oro-platform-logo.svg
icon: bundles/acmetheme/themes/oro/images/favicon.ico
rtl_support: true
styles:
    css:
        inputs:
            - bundles/acmetheme/themes/demo/css/scss/settings/primary-settings
        output: css/oro.css
