datagrids:
    frontend-training-quotes-grid:
        extends: frontend-quotes-grid
        options:
            jsmodules:
                - trainingfrontendtraining/js/app/datagrid/listener/refresh-grid-listener
