datagrids:
    frontend-training-quotes-grid:
        extends: frontend-quotes-grid
        options:
            jsmodules:
                - trainingfrontendtraining/js/app/datagrid/listener/refresh-grid-listener
    frontend-customer-user-shopping-list-grid:
        options:
            jsmodules:
                - trainingfrontendtraining/js/datagrid/builder/csr-badge-shopping-list-flat-data-builder

    frontend-checkout-line-items-grid:
        options:
            jsmodules:
                - trainingfrontendtraining/js/datagrid/builder/csr-badge-shopping-list-flat-data-builder
