training_bundle_frontendtraining_frontend_shoppinglistcleanup:
    resource:     "@TrainingFrontendTrainingBundle/Controller/Frontend/ShoppingListCleanupController.php"
    type:         annotation
    prefix:       /shoppinglist
    options:
        frontend: true
