training_bundle_frontendtraining_frontend_shoppinglistcleanup:
    resource:     "@TrainingFrontendTrainingBundle/Controller/Frontend/ShoppingListCleanupController.php"
    type:         annotation
    prefix:       /shoppinglist
training_frontend_training_dashboard:
    resource:     "@TrainingFrontendTrainingBundle/Controller/Frontend/DashboardController.php"
    type:         annotation
    prefix:       /frontend-dashboard
    options:
        frontend: true
