services:
    _defaults:
        public: true

    Acme\Bundle\FrontendLibrariesBundle\Controller\Frontend\CountryController:
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: container.service_subscriber }
