services:
    TC\Bundle\UserBundle\Helper\UserNameHelper: ~

    TC\Bundle\UserBundle\Async\UserFullNameExtendedProcessor:
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@TC\Bundle\UserBundle\Helper\UserNameHelper'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    TC\Bundle\UserBundle\EventListener\UserListener:
        arguments:
            - '@oro_message_queue.client.message_producer'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\UserBundle\Entity\User', event: postPersist }
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\UserBundle\Entity\User', event: preUpdate }
