parameters:
    environment_indicator: '%env(ENVIRONMENT_INDICATOR)%'

services:
    TC\Bundle\ConfigBundle\Twig\ParametersExtension:
        arguments:
            - '@parameter_bag'
        tags:
            - { name: twig.extension }
