configs:
    acmesearchdatagridrefresh/js/app/components/layout-block-refresh-component: {}

dynamic-imports:
    acmesearchdatagridrefresh:
        - acmesearchdatagridrefresh/js/app/components/layout-block-refresh-component
