services:
    _defaults:
        public: true

    Training\Bundle\UserNamingBundle\Controller\UserNamingController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
